name: Publish Npm Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup version node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.2'
          
      - name: Install dependencies
        run: npm i

                              

        
